server:
  port: 85 # 服务端口
  
spring:
 application:
    name: microservice-cloud-07-feign

eureka:
  client:
    serviceUrl:    # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群版
      defaultZone: http://eureka6001.com:6001/eureka/

feign:
  hystrix:
    enabled: true
  
